apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: kustomize-simple
spec:
  schema:
    apiVersion: v1alpha1
    kind: KustomizeSimple
    spec:
      prefix: string | default="kustomize-simple"
  resources:
    - id: resourceChart
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: "${schema.spec.prefix}-resource-chart-name"
        spec:
          componentRef:
            name: kustomize-simple-component
          resource:
            byReference:
              resource:
                name: kustomize-resource
          interval: 10m
    - id: ocirepository
      template:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: OCIRepository
        metadata:
          name: "${schema.spec.prefix}-oci-repository-name"
        spec:
          interval: 1m0s
          insecure: true
          layerSelector:
            mediaType: "application/vnd.oci.image.layer.v1.tar+gzip"
            operation: copy
          url: oci://${resourceChart.status.reference.registry}/${resourceChart.status.reference.repository}
          ref:
            tag: ${resourceChart.status.reference.reference}
    - id: kustomization
      template:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: "${schema.spec.prefix}-kustomization-name"
        spec:
          targetNamespace: default
          interval: 1m
          prune: true
          sourceRef:
            kind: OCIRepository
            name: ${ocirepository.metadata.name}
            namespace: default
