apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-gitops
  namespace: default
spec:
  interval: 5m
  url: https://github.com/frewilhelm/ocm-k8s-toolkit
  ref:
    branch: demo_branch
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-gitops
spec:
  targetNamespace: default
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo-gitops
  path: "demo-gitops/kustomize"