apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kustomize-demo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/frewilhelm/ocm-k8s-toolkit
  ref:
    branch: demo_branch
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-demo
spec:
  targetNamespace: default
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: kustomize-demo
  path: "demo-kustomize/kustomize"