apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: two-graphs-one-resource-one-rgd
spec:
  schema:
    apiVersion: v1alpha1
    kind: TwoGraphsOneResourceOne
    spec:
      prefix: string | default="two-graphs-one-resource-one"
  resources:
    - id: resourceChart
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: "${schema.spec.prefix}-resource-chart-name"
        spec:
          componentRef:
            name: static-component-name
          resource:
            byReference:
              resource:
                name: helm-resource
          interval: 10m