---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m0s
  layerSelector:
    mediaType: "application/vnd.oci.image.layer.v1.tar+gzip"
    operation: copy
  url: oci://ocm-k8s-toolkit-zot-registry.ocm-k8s-toolkit-system.svc.cluster.local:5000/sha-2744483177395971398
  ref:
    tag: "6.7.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: podinfo
    namespace: default